version: 2

jobs:
  build:
    parallelism: 1
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'venv'
      - restore_cache:
          keys:
            - 'tox-{{ checksum "tox.ini" }}'
      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -U tox
          tox
      - save_cache:
          key: 'tox-{{ checksum "tox.ini" }}'
          paths:
            - .tox
      - save_cache:
          key: 'venv'
          paths:
            - .venv
      - store_test_results:
          path: .tox/py37/artifacts/
  # Deploy to pypi!
  # deploy:
