version: 2

jobs:
  build:
    parallelism: 1
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'tox-{{ checksum "tox.ini" }}'
      - run: pip install -U --user tox
      - run: tox
      - save_cache:
          key: 'tox-{{ checksum "tox.ini" }}'
          paths:
            - .tox
      - store_test_results:
          path: .tox/py37/artifacts/
  # Deploy to pypi!
  # deploy:
